### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by anthodemorais** [anthodemorais/shareyoursound#29]
- Changer les boutons en like / dislike dans la page d'un media (Maxime)
- Changer le header en enlevant login et register si un token est dans le local storage (Maxime)
- Rediriger vers la page d'accueil quand un id dans l'url est mauvais (Anthony)
- Changer la page d'accueil pour mettre la liste des musiques si on est connecté sinon mettre login (Maxime)
- Mettre à jour la page quand on ajoute / supprime un type (Anthony)

**Comment by Maximetra** [comment]
C'est fini !
